version: '3'
services:
    client:
        build: ./client
        image: client-image
        container_name: client
        tty: true
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/usr/src/app
        ports:
            - "3000:3000"
        working_dir: /usr/src/app/client/img_uploader
    
    server:
        build: ./server
        image: server-image
        container_name: server
        tty: true
        volumes:
            - ./server:/usr/src/app
        ports:
            - "8000:8000"
        working_dir: /usr/src/app
